name: iOS Starter Workflow with Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Swift Code
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Swift
        run: |
          swift --version

      - name: Compile Swift Files
        run: |
          cd src
          swiftc -o output *.swift

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }} # Use github.ref_name for the release name
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }} # Pass the token here directly
